# virtualenvwrapper
_LOCAL_BIN=$HOME/.local/bin
export VIRTUALENVWRAPPER_PYTHON=$_LOCAL_BIN/python
export VIRTUALENVWRAPPER_VIRTUALENV=$_LOCAL_BIN/virtualenv
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
source $_LOCAL_BIN/virtualenvwrapper.sh 
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true

# work stuff
export SIQ_PROJECT_PATH=$PROJECT_HOME/siq
